name: markup_text
description: Flutter widget to use Markup to easily create formatted Text with colors, style and links.
version: 1.0.3-dev.1
homepage: https://github.com/poqueque/markup_text

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: